### ISSUE TITLE
Implementing rubysys with Artichoke Ruby

### ISSUE THREAD

**Issue by lopopolo** [danielpclark/rutie#98]
Hi 👋 rutie looks amazing and I'm hoping we can work together.

I'm building a Ruby in Rust called [Artichoke](https://github.com/artichoke/artichoke). The `rubysys` module in rutie looks really interesting and I am hoping I can find a way to use it to expose a `libruby.a` compatible static build of Artichoke. I want to run nokogiri.

Is it possible to extract `rubysys` into a crate? Would it be better to fork rutie?

I have a ticket in Artichoke if you'd like to discuss this further there: https://github.com/artichoke/artichoke/issues/88

**Comment by lopopolo** [comment]
The Artichoke README currently lists MRI C API compatibility as a non-goal, but I only did so because I thought it would be hard. Maybe it is easier than I thought it would be?

**Comment by danielpclark** [comment]
Hey, I just saw this.  You could extract it, but it already exists: https://github.com/steveklabnik/ruby-sys .  There has been a bunch of changes to it since then though so it's more up to date here.  You may extract it as per the MIT license agreement but you would need the license to include a line for both Steve Klabnik, Dmitry Gritsay, and for myself Daniel P. Clark.

**Comment by lopopolo** [comment]
Thank you @danielpclark this answers my question, I'll close this issue.
